### ISSUE TITLE
boilerplate_psg not found when running designer, after using pip install 

### ISSUE THREAD

**Issue by mbusch-regis** [nngogol/PySimpleGUIDesigner#1]
I did a pip install PySimpleGUIDesigner, which returned 
```
Installing collected packages: shiboken2, PySide2, PySimpleGUIDesigner
Successfully installed PySide2-5.12.3 PySimpleGUIDesigner-0.0.2 shiboken2-5.12.3

```
Then on a new command line:

```
mbusch@Mikes-MacBook-Pro ~ $ PySimpleGUIDesigner
Traceback (most recent call last):
  File "/Users/mbusch/anaconda3/bin/PySimpleGUIDesigner", line 7, in <module>
    from PySimpleGUIDesigner.main import cli
  File "/Users/mbusch/anaconda3/lib/python3.7/site-packages/PySimpleGUIDesigner/main.py", line 1, in <module>
    from boilerplate_psg import boilerplate_
ModuleNotFoundError: No module named 'boilerplate_psg'
mbusch@Mikes-MacBook-Pro ~ $
```

Did I miss a step?

**Comment by nngogol** [comment]
Thanks for this!
I already fix it!
Try (for python3):
pip3 install -U PySimpleGUIDesigner --user
-U - will update library
