### ISSUE TITLE
Exception: error, no obj_name="MainWindow" found

### ISSUE THREAD

**Issue by benl134** [nngogol/PySimpleGUIDesigner#14]
Both main_for_devel.py and PySimpleGUIDesigner throw the exception above

full error
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/PySimpleGUIDesigner/__main__.py", line 4, in <module>
    cli()
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/PySimpleGUIDesigner/real_src_here.py", line 697, in cli
    run_gui()
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/PySimpleGUIDesigner/real_src_here.py", line 602, in run_gui
    ui = just_compile(values)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/PySimpleGUIDesigner/real_src_here.py", line 142, in just_compile
    raise Exception(f'error, no obj_name="{OBJ_NAME}" found')
Exception: error, no obj_name="MainWindow" found
```

**Comment by nngogol** [comment]
Hello.
Can you provide your .ui file?
Did you read the manual? Can you make a good issue?
