### ISSUE TITLE
no obj_name="verticalLayout" found

### ISSUE THREAD

**Issue by faberf** [nngogol/PySimpleGUIDesigner#20]
I followed your youtube tutorial (thank you btw) and downloaded qt designer. I made two grid layouts with pushbuttons, list widgets, tab widgets and a graphics view and put both of them in a vertical layout. Now I open PySimpleGUIDesigner, select my .ui file, select verticalLayout from the dropdown and press convert. PySimpleGUIDesigner crashes and on the command line I read:

Traceback (most recent call last):
  File "/home/faberf/anaconda3/envs/general/bin/PySimpleGUIDesigner", line 8, in <module>
    sys.exit(cli())
  File "/home/faberf/anaconda3/envs/general/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/faberf/anaconda3/envs/general/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/faberf/anaconda3/envs/general/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/faberf/anaconda3/envs/general/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/faberf/anaconda3/envs/general/lib/python3.8/site-packages/PySimpleGUIDesigner/real_src_here.py", line 697, in cli
    run_gui()
  File "/home/faberf/anaconda3/envs/general/lib/python3.8/site-packages/PySimpleGUIDesigner/real_src_here.py", line 602, in run_gui
    ui = just_compile(values)
  File "/home/faberf/anaconda3/envs/general/lib/python3.8/site-packages/PySimpleGUIDesigner/real_src_here.py", line 142, in just_compile
    raise Exception(f'error, no obj_name="{OBJ_NAME}" found')
Exception: error, no obj_name="verticalLayout" found

I am running python 3.8.5, PySimpleGUIDesigner 0.1.4.7. This issue persists even when I select other object names.

**Comment by nngogol** [comment]
Hi. Did you really watched a video? Have you placed items INTO QVBoxLayout? Send a .ui file.
