### ISSUE TITLE
No Module named 'click'

### ISSUE THREAD

**Issue by the-cannoli** [nngogol/PySimpleGUIDesigner#7]
Running into the following issue when launching PySimpleGUIDesigner I just installed PySide2 and PySimpleGUIDesigner using PIP.

```
U:\>PySimpleGUIDesigner
Traceback (most recent call last):
  File "c:\users\*******\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\*******\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python37-32\Scripts\PySimpleGUIDesigner.exe\__main__.py", line 4, in <module>
  File "c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages\PySimpleGUIDesigner\main.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by nngogol** [comment]
Install click module by running: `pip install click`
Tell me, if it helped.

**Comment by the-cannoli** [comment]
I'll be honest. Not sure why I didn't think of that. That worked like a charm. Thanks.
