### ISSUE TITLE
ProblemToConvert

### ISSUE THREAD

**Issue by milen-prg** [nngogol/PySimpleGUIDesigner#8]
I use WinPython 3.8 64bit with PyQt5. So I edit the installed files of PySimpleGUIDesigner to change PySide to PyQt5. So the GUI starts, but when I try to convert the example .ui file:

---
D:\newInstalled\WPy64-3800\scripts>PySimpleGUIDesigner
Traceback (most recent call last):
  File "D:\newInstalled\WPy64-3800\python-3.8.0.amd64\lib\runpy.py", line 192, i
n _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\newInstalled\WPy64-3800\python-3.8.0.amd64\lib\runpy.py", line 85, in
 _run_code
    exec(code, run_globals)
  File "D:\newInstalled\WPy64-3800\python-3.8.0.amd64\Scripts\PySimpleGUIDesigne
r.exe\__main__.py", line 7, in <module>
  File "D:\newInstalled\WPy64-3800\python-3.8.0.amd64\lib\site-packages\click\co
re.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "D:\newInstalled\WPy64-3800\python-3.8.0.amd64\lib\site-packages\click\co
re.py", line 717, in main
    rv = self.invoke(ctx)
  File "D:\newInstalled\WPy64-3800\python-3.8.0.amd64\lib\site-packages\click\co
re.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\newInstalled\WPy64-3800\python-3.8.0.amd64\lib\site-packages\click\co
re.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "D:\newInstalled\WPy64-3800\python-3.8.0.amd64\lib\site-packages\PySimple
GUIDesigner\main.py", line 602, in cli
    run_gui()
  File "D:\newInstalled\WPy64-3800\python-3.8.0.amd64\lib\site-packages\PySimple
GUIDesigner\main.py", line 508, in run_gui
    ui = just_compile(values)
  File "D:\newInstalled\WPy64-3800\python-3.8.0.amd64\lib\site-packages\PySimple
GUIDesigner\main.py", line 149, in just_compile
    raise Exception(f'error, no obj_name="{OBJ_NAME}" found')
Exception: error, no obj_name="g2" found

D:\newInstalled\WPy64-3800\scripts>
---
The D:\newInstalled\WPy64-3800 is the WinPython folder.

**Comment by nngogol** [comment]
DON'T. INSTALL. PyQt5.
Install pyside2.
Please, readme the `readme.md - install section`.

**Comment by bburns8** [comment]
i am also having this problem with "no obj_name=groupBox found". i am using pyside2 and dont have PyQt5 installed. any idea what my problem might be?
