### ISSUE TITLE
ModuleNotFoundError: No module named 'PySide2'

### ISSUE THREAD

**Issue by zsp1123** [nngogol/PySimpleGUIDesigner#9]
C:\Users\zsp>pysimpleguidesigner
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\PySimpleGUIDesigner.exe\__main__.py", line 4, in <module>
  File "c:\anaconda3\lib\site-packages\PySimpleGUIDesigner\main.py", line 13, in <module>
    from .transpiler2 import *
  File "c:\anaconda3\lib\site-packages\PySimpleGUIDesigner\transpiler2.py", line 1, in <module>
    from PySide2 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PySide2'

I changed all "PySide2" to "PyQt5" in "c:\anaconda3\lib\site-packages\PySimpleGUIDesigner\transpiler2.py" ,then the program could run.

**Comment by nngogol** [comment]
No, just install pyside2 - it's a different package.
Closing the issue.
